version: 0.2

# env:
#   variables:
#     JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
#   parameter-store:
#     LOGIN_PASSWORD: /CodeBuild/dockerLoginPassword

phases:
  install:
    commands:
      - echo Installing Maven
      - apt-get update -y
      - apt-get install -y maven
      - echo Authenticating Docker on ECR
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $TARGET_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$TARGET_REGION.amazonaws.com
    # finally:
    #   - echo This always runs even if the update or install command fails 
  # pre_build:
  #   commands:
  #     - echo Entered the pre_build phase...
  #     - docker login -u User -p $LOGIN_PASSWORD
  #   finally:
  #     - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase
      - echo Build started on `date`
      - mvn compile dependency:copy-dependencies -DincludeScope=runtime
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$TARGET_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
    # finally:
    #   - echo This always runs even if the install command fails
      - 
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$TARGET_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Build completed on `date`

# reports:
#   arn:aws:codebuild:your-region:your-aws-account-id:report-group/report-group-name-1:
#     files:
#       - "**/*"
#     base-directory: 'target/tests/reports'
#     discard-paths: no
#   reportGroupCucumberJson:
#     files:
#       - 'cucumber/target/cucumber-tests.xml'
#     discard-paths: yes
#     file-format: CUCUMBERJSON # default is JUNITXML
# artifacts:
#   files:
#     - target/messageUtil-1.0.jar
#   discard-paths: yes
#   secondary-artifacts:
#     artifact1:
#       files:
#         - target/artifact-1.0.jar
#       discard-paths: yes
#     artifact2:
#       files:
#         - target/artifact-2.0.jar
#       discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
