version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo Entered the build phase
      - echo Build started on `date`
      - mvn package
artifacts:
 files:
   - target/crypto-trader.jar
   - appspec.yml
cache:
  paths:
    - '/root/.m2'
