AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sam Stack for Crypto Trader
Resources:
  CryptoTrader:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Handler: com.github.marceloleite2604.cryptotrader.CryptoRequestHandler::handleRequest
      Timeout: 60
      MemorySize: 512
      CodeUri: ./target/crypto-trader.jar
      AutoPublishAlias: prod
      DeploymentPreference:
        Type: AllAtOnce
      Environment:
        Variables:
          CLIENT_ID: "{{resolve:ssm:/lambda-crypto-trader/client-id}}"
          CLIENT_SECRET: "{{resolve:ssm:/lambda-crypto-trader/client-secret}}"
          EMAIL_HOST: "{{resolve:ssm:/lambda-crypto-trader/email-host}}"
          EMAIL_PASSWORD: "{{resolve:ssm:/lambda-crypto-trader/email-password}}"
          EMAIL_PORT: "{{resolve:ssm:/lambda-crypto-trader/email-port}}"
          EMAIL_RECIPIENTS: "{{resolve:ssm:/lambda-crypto-trader/email-recipients}}"
          EMAIL_USERNAME: "{{resolve:ssm:/lambda-crypto-trader/email-username}}"
  ScheduleDailyAt3AmUtc:
    Type: AWS::Events::Rule
    Properties:
      Description: "Event triggered everyday at 3 AM UTC"
      ScheduleExpression: "cron(0 3 * * ? *)"
      State: "ENABLED"
      Targets:
        -
          Id: "CryptoTraderExecution"
          Arn:
            Fn::Join:
              - ':'
              - - Fn::GetAtt:
                  - "CryptoTrader"
                  - "Arn"
                - "prod"
          Input: |-
            {
                "path": "/",
                "httpMethod": "GET"
            }
          RetryPolicy:
            MaximumEventAgeInSeconds: 3600
            MaximumRetryAttempts: 2
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::Join:
          - ':'
          - - Fn::GetAtt:
              - "CryptoTrader"
              - "Arn"
            - "prod"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduleDailyAt3AmUtc"
          - "Arn"