AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Crypto Trader
Resources:
  cryptoTrader:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Handler: com.github.marceloleite2604.cryptotrader.CryptoRequestHandler::handleRequest
      Timeout: 60
      MemorySize: 512
      CodeUri: ./target/crypto-trader.jar
      AutoPublishAlias: prod
      DeploymentPreference:
        Type: AllAtOnce
      Environment:
        Variables:
          CLIENT_ID: "{{resolve:ssm-secure:/lambda-crypto-trader/client-id}}"
          CLIENT_SECRET: "{{resolve:ssm-secure:/lambda-crypto-trader/client-secret}}"
          EMAIL_HOST: "{{resolve:ssm-secure:/lambda-crypto-trader/email-host}}"
          EMAIL_PASSWORD: "{{resolve:ssm-secure:/lambda-crypto-trader/email-password}}"
          EMAIL_PORT: "{{resolve:ssm-secure:/lambda-crypto-trader/email-port}}"
          EMAIL_RECIPIENTS: "{{resolve:ssm-secure:/lambda-crypto-trader/email-recipients}}"
          EMAIL_USERNAME: "{{resolve:ssm-secure:/lambda-crypto-trader/email-username}}"