AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Crypto Trader
Parameters:
  MbClientId:
    Type: String
  MbClientSecret:
    Type: String
  EmailHost:
    Type: String
  EmailPassword:
    Type: String
  EmailPort:
    Type: String
  EmailRecipients:
    Type: String
  EmailUsername:
    Type: String
Resources:
  cryptoTrader:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Handler: com.github.marceloleite2604.cryptotrader.CryptoRequestHandler::handleRequest
      Timeout: 60
      MemorySize: 512
      CodeUri: ./target/crypto-trader.jar
      AutoPublishAlias: prod
      DeploymentPreference:
        Type: AllAtOnce
      Environment:
        Variables:
          CLIENT_ID: !Ref MbClientId
          CLIENT_SECRET: !Ref MbClientSecret
          EMAIL_HOST: !Ref EmailHost
          EMAIL_PASSWORD: !Ref EmailPassword
          EMAIL_PORT: !Ref EmailPort
          EMAIL_RECIPIENTS: !Ref EmailRecipients
          EMAIL_USERNAME: !Ref EmailUsername